version: "3.4"
services:

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=${TP_THEME}
    volumes:
      - ${ROOT}/downloads/blackhole:/downloads
      - ${ROOT}/config/prowlarr:/config
    ports:
      - 9696:9696

  sonarr:
    container_name: sonarr
    image: ghcr.io/mdhiggins/sonarr-sma:develop
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=${TP_THEME}
      - SMA_HWACCEL=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config
      - ${ROOT}/config/sma:/usr/local/sma/config
      - ${ROOT}/downloads/complete/tv:/tv
      - ${ROOT}/downloads:/downloads
    ports:
      - 8989:8989
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/video18:/dev/video18
      - /dev/video31:/dev/video31
      - /dev/dri:/dev/dri

  radarr:
    container_name: radarr
    image: ghcr.io/mdhiggins/radarr-sma:develop
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=${TP_THEME}
      - SMA_HWACCEL=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config
      - ${ROOT}/config/sma:/usr/local/sma/config
      - ${ROOT}/downloads/complete/movies:/movies
      - ${ROOT}/downloads:/downloads
    ports:
      - 7878:7878
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/video18:/dev/video18
      - /dev/video31:/dev/video31
      - /dev/dri:/dev/dri

  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
#      - DOCKER_MODS=ghcr.io/gilbn/theme.park:jellyfin
#      - TP_THEME=${TP_THEME}
    volumes:
      - ${ROOT}/config/jellyfin:/config
      - ${ROOT}/downloads/complete/tv:/data/tvshows
      - ${ROOT}/downloads/complete/movies:/data/movies
    ports:
      - 8096:8096
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/video18:/dev/video18
      - /dev/video31:/dev/video31
      - /dev/dri:/dev/dri

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:overseerr
      - TP_THEME=${TP_THEME}
    volumes:
      - ${ROOT}/config/jellyseerr:/app/config
    ports:
      - 5055:5055

  nzbget:
    container_name: nzbget
    image: lscr.io/linuxserver/nzbget:testing
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:nzbget
      - TP_THEME=${TP_THEME}
    volumes:
      - ${ROOT}/downloads:/downloads
      - ${ROOT}/config/nzbget:/config
      - ${ROOT}/config/scripts:/scripts
    ports:
      - 6789:6789

  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: host # service:vpn to run on the vpn network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:deluge
      - TP_THEME=${TP_THEME}
    volumes:
      - ${ROOT}/downloads:/downloads
      - ${ROOT}/config/deluge:/config
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8191:8191

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:development
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:bazarr
      - TP_THEME=${TP_THEME}
    volumes:
      - ${ROOT}/config/bazarr:/config
      - ${ROOT}/downloads/complete/movies:/movies
      - ${ROOT}/downloads/complete/tv:/tv
    ports:
      - 6767:6767

  flame:
    container_name: flame
    image: pawelmalak/flame:multiarch
    restart: unless-stopped
    network_mode: host
    environment:
      - PASSWORD=${FLAME_PASSWORD}
    volumes:
      - ${ROOT}/config/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005:5005

#
# **Dropped in favour of flame**
#
#  homarr:
#    container_name: homarr
#    image: ghcr.io/ajnart/homarr:latest
#    restart: unless-stopped
#    network_mode: host
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - ${ROOT}/config/homarr:/app/data/configs
#    ports:
#      - 7575:7575

#
# **Prioritise usenet over torrents so a vpn is not needed**
#
#  vpn:
#    container_name: vpn
#    image: dperson/openvpn-client:latest
#    cap_add:
#      - net_admin # required to modify network interfaces
#    restart: unless-stopped
#    volumes:
#      - /dev/net:/dev/net:z
#      - ${ROOT}/config/vpn:/vpn
#    security_opt:
#      - label:disable
#    ports:
#      - 8112:8112 # port for deluge web UI to be reachable from local network
#    command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic

#
# **Dropped in favour of jellyfin**
#
#  plex-server:
#    container_name: plex-server
#    image: lscr.io/linuxserver/plex:latest
#    restart: unless-stopped
#    network_mode: host
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#      - VERSION=docker
#      - DOCKER_MODS=ghcr.io/gilbn/theme.park:plex
#      - TP_THEME=${TP_THEME}
#    volumes:
#     - ${ROOT}/config/plex/db:/config
#      - ${ROOT}/config/plex/transcode:/transcode
#      - ${ROOT}/downloads/complete:/data
#    ports:
#      - 32400:32400

#
# **Incompatiable with jellyfin - use jellyseerr instead**
#
#  overseerr:
#    container_name: overseerr
#    image: lscr.io/linuxserver/overseerr:latest
#    restart: unless-stopped
#    network_mode: host
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#      - DOCKER_MODS=ghcr.io/gilbn/theme.park:overseerr
#      - TP_THEME=${TP_THEME}
#    volumes:
#      - ${ROOT}/config/overseerr:/config
#    ports:
#      - 5055:5055

#
# **Couldn't get it to work well - videos transcoded once downloaded using sma**
#
#  unmanic:
#    container_name: unmanic
#    image: josh5/unmanic:latest
#    restart: unless-stopped
#    network_mode: host
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - ${ROOT}/config/unmanic:/config
#      - ${ROOT}/downloads/complete:/library
#      - ${ROOT}/downloads/tmp:/tmp/unmanic
#    devices:
#      - /dev/dri:/dev/dri
